SidecarPort: "8003"
CommandPrefix: ""
ExportPodData: true
DataRootFolder: ".knoc/"
VKTokenFile: "/opt/interlink/token"
InterlinkAddress: "http://localhost"
SidecarURL: "http://localhost"
ServiceAccount: "interlink"
BashPath: /bin/bash
ErrorsOnlyLogging: false

InterlinkURL: "http://localhost"
InterlinkPort: "30004" 
VerboseLogging: true
ErrorsOnlyLogging: false
ServiceAccount: "interlink"
Namespace: interlink 
Resources:
  CPU: "1000"
  Memory: "16000Gi"
  Pods: "1000"
HTTP:
  Insecure: true
KubeletHTTP:
  Insecure: true